tickers: 
  - 'SPY'
  - 'VIXY'
start_year: 2024
indicators_for_tickers: 
    - 'SPY'
    - 'VIXY'
indicators: 
  - name: 'ma'
    params:
      period: 14
  - name: 'rsi'
    params:
      period: 14
  - name: 'bb'
    params:
      period: 20
      num_std_dev: 2
  - name: 'macd'
    params:
      short_window: 12
      long_window: 26
      signal_window: 9
  # - name: 'adx'
  #   params:
  #     period: 14
  - name: 'stoch'
    params:
      period: 14
      smooth_k: 3
      smooth_d: 3
paths: 
  raw: 'data/raw'  
  processed: 'data/processed'
