indicators:
- name: ma
  params:
    period: 14
- name: rsi
  params:
    period: 14
- name: bb
  params:
    num_std_dev: 2
    period: 20
- name: macd
  params:
    long_window: 26
    short_window: 12
    signal_window: 9
- name: stoch
  params:
    period: 14
    smooth_d: 3
    smooth_k: 3
- name: vol
  params:
    period: 60
indicators_for_tickers:
- SPY
- VIXY
paths:
  analysis: analysis
  plots: analysis/plots
  processed: data/processed
  raw: data/raw
sequence_length: 60
start_year: 2022
tickers:
- SPY
- VIXY
train_size: 0.7
val_size: 0.1
y_column: SPY_vol
